export const sample_foods = [
  {
    id: "1",
    name: "پیتزا",
    cookTime: "10-20",
    price: 180000,
    favorite: false,
    origins: ["ایتالیا"],
    stars: 4,
    imageUrl: "assets/images/food-1.jpg",
    tags: ["فست فود", "پیتزا", "همه"],
  },
  {
    id: "2",
    name: "کوفته",
    price: 115000,
    cookTime: "20-30",
    favorite: true,
    origins: ["آسیا", "ایران", "چین"],
    stars: 4,
    imageUrl: "assets/images/food-2.jpg",
    tags: ["غذای راحت", "ناهار", "همه"],
  },
  {
    id: "3",
    name: "همبرگر",
    price: 187000,
    cookTime: "10-15",
    favorite: false,
    origins: ["المان", "آمریکا"],
    stars: 3,
    imageUrl: "assets/images/food-3.jpg",
    tags: ["فستفود", "همبرگر", "همه"],
  },
  {
    id: "4",
    name: "سیبزمینی سرخ کرده",
    price: 120000,
    cookTime: "15-20",
    favorite: true,
    origins: ["بلژیک", "فرانسه"],
    stars: 3,
    imageUrl: "assets/images/food-4.jpg",
    tags: ["فستفود", "سرخ شده", "همه"],
  },
  {
    id: "5",
    name: "سوپ مرغ",
    price: 130000,
    cookTime: "40-50",
    favorite: false,
    origins: ["هند", "آسیا"],
    stars: 3.0,
    imageUrl: "assets/images/food-5.jpg",
    tags: ["غذای راحت", "سوپ", "همه"],
  },
  {
    id: "6",
    name: "پیتزا سبزیجات",
    price: 250000,
    cookTime: "40-50",
    favorite: false,
    origins: ["ایتالیا"],
    stars: 4.0,
    imageUrl: "assets/images/food-6.jpg",
    tags: ["فستفود", "پیتزا", "ناهار", "همه"],
  },
  {
    id: "7",
    name: "همبرگر پنیر",
    price: 270000,
    cookTime: "20-30",
    favorite: false,
    origins: ["هند"],
    stars: 4.0,
    imageUrl: "assets/images/food-7.jpg",
    tags: ["فستفود", "همبرگر", "ناهار", "همه"],
  },
  {
    id: "8",
    name: "پیتزا سبزیجات",
    price: 139000,
    cookTime: "45-50",
    favorite: false,
    origins: ["هند"],
    stars: 4.0,
    imageUrl: "assets/images/food-8.jpg",
    tags: ["فستفود", "پیتزا", "ناهار", "همه"],
  },
];

export const sample_tags = [
  { name: "همه", count: 8 },
  { name: "فستفود", count: 4 },
  { name: "پیتزا", count: 3 },
  { name: "ناهار", count: 3 },
  { name: "غذای راحت", count: 2 },
  { name: "همبرگر", count: 2 },
  { name: "سرخکردنی", count: 1 },
  { name: "سوپ", count: 1 },
];
export const sample_users = [
  {
    name: "کاربر عادی",
    email: "bahareh@gmail.com",
    password: "123456",
    address: "iran",
    isAdmin: true,
  },
  {
    name: "kia",
    email: "kia.kia@gmail.com",
    password: "123456@",
    address: "iran",
    isAdmin: false,
  },
];
